config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  devise_for :users
  root "phones#index"
  resources :phones, only: [:show, :index]
  resources :categories, only: [:show]

  namespace :admin do
    resources :categories, except: [:show]
    resources :phones, except: [:show, :index]
  end

end

app/models/phone.rb
class Phone < ApplicationRecord
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  mount_uploader :image, ImageUploader
  validates :name, :price, :description, presence: true
  validates :price, numericality: {greater_than: 0, allow_nil: true}

  belongs_to :category, optional: true

  private

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end

end

app/controllers/admin/phones_controller.rb
class Admin::PhonesController < Admin::AdminController
before_action :set_phone, only: [ :edit, :update, :destroy]

  def new
    @phone=Phone.new
  end

  def create
    @phone=Phone.new(phone_params)
    if @phone.save
      redirect_to  @phone, success: 'Телефон успешно создан'
    else
      flash.now[:danger] = 'Телефон не создан'
      render :new
    end
  end

  def edit
  end

  def update
    if @phone.update_attributes(phone_params)
      redirect_to @phone, success: 'Телефон успешно обновлен'
    else
      flash.now[:danger] = 'Телефон не обновлен'
      render :edit
    end
  end

  def destroy
    @phone.destroy
    redirect_to phones_path, success: 'Телефон успешно удален'
  end

  private

  def set_phone
    @phone=Phone.find(params[:id])
  end

    def phone_params
      params.require(:phone).permit(:name, :price, :description, :image, :category_id)
    end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [ :show]

  def index
    @phones =Phone.all
  end

  def show
  end

  private

  def set_phone
    @phone=Phone.find(params[:id])
  end
end

app/helpers/phone_helper.rb
module PhoneHelper
end

app/views/phones/_form.html.erb
<% if @phone.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors')%></h5>
    <ul>
      <% @phone.errors.full_messages.each do |message|%>
        <li><%=message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

<%= form_for @phone, html: {multipart: true} do |f| %>
  <div class="form-group">
    <%=f.label :name %>
    <%=f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%=f.label :price %>
    <%=f.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%=f.label :description %>
    <%=f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%=f.label :category_id %>
    <%=f.collection_select :category_id, Category.order(:name), :id, :name, {include_blank: true}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%=f.file_field :image %>
  </div>

  <div class="form-group">
  <%= f.submit t('.submit', action: @phone.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary'%>
    <%=link_to t('common.back') , :back, class: 'btn btn-outline-secondary'%>
  </div>



<%end %>

app/views/phones/_phone.html.erb
<product class="phone">
  <section class="phone-head">
    <h2><%=link_to phone.name, phone_path(phone) %></h2>
    <small>
      <time><%=phone.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if phone.category.present? %>
       |
      <%=link_to phone.category.name, phone.category %>
      <%end %>
      <% if user_signed_in? && current_user.admin? %>
      |
      <%=link_to 'Изменить', edit_admin_phone_path(phone) %>
      |
      <%=link_to 'Удалить', admin_phone_path(phone),
                method: :delete, data: {confirm: 'Вы уверены?'} %>
      <% end %>
    </small>
  </section>
  <section class="phone-price">
    <%=phone.price %> грн
  </section>
</product>

app/views/phones/index.html.erb
<h1><%= t('.name') %></h1>
<% if user_signed_in? && current_user.admin? %>

  <%= link_to 'Добавить телефон', new_admin_phone_path, class: 'btn btn-outline-primary btn-sm'%>
<% end %>
  <section id='phones'>
  <%= render @phones %>
</section>

app/views/phones/show.html.erb
<%=render 'shared/breadcrumb', category: @phone.category %>

<product class="phone">
  <section class="phone-head">
    <h1><%=@phone.name %></h1>
    <small>
      <time><%= @phone.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if @phone.category.present? %>
      |
       <%= link_to @phone.category.name, @phone.category %>
      <% end %>
      <% if user_signed_in? && current_user.admin? %>
      |
      <%=link_to 'Изменить', edit_admin_phone_path(@phone) %>
      |
      <%=link_to 'Удалить', admin_phone_path(@phone),
                 method: :delete, data: {confirm: 'Вы уверены?'} %>
        <% end %>
        </small>
  </section>
  <section class="phone-price">
    <%=@phone.price %> грн
  </section>
  <section class="phone-description">
    <%=image_tag  @phone.image.url(:thumb), class: 'img-show' if @phone.image? %>
    <%=@phone.description %>
    <%= button_to 'Add to cart', line_items_path(phone_id: @phone), class: 'btn btn-warning'%>
  </section>
</product>